name: kori_etu
description: "KORI etudiant App"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  smooth_page_indicator: ^1.2.0+3
  hugeicons: ^0.0.7
  intl_phone_field: ^3.2.0
  mask_text_input_formatter: ^2.9.0
  flutter_launcher_icons: ^0.13.1
  go_router: ^14.2.7
  flutter_native_splash: ^2.4.2
  animations: ^2.0.11
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  get_storage: ^2.1.1
  google_sign_in: ^6.2.2
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  either_dart: ^1.0.0
  sign_in_with_apple: ^6.1.3
  url_launcher: ^6.3.1
  device_info_plus: ^11.1.1
  loading_animation_widget: ^1.3.0
  ip_country_lookup: ^1.0.3
  get_it: ^8.0.2
  logger: ^2.5.0
  local_auth: ^2.3.0
  cached_network_image: ^3.4.1
  flutter_masked_text2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/kori_logo_tranparant.png
    - assets/images/kori_logo.png
    - assets/images/
    - assets/json/all_countries.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: FamiljenGrotesk
      fonts:
        - asset: assets/fonts/famijen/FamiljenGrotesk-Medium.ttf
          weight: 500
        - asset: assets/fonts/famijen/FamiljenGrotesk-Regular.ttf
          weight: 400
        - asset: assets/fonts/famijen/FamiljenGrotesk-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/famijen/FamiljenGrotesk-Bold.ttf
          weight: 700


    - family: inter
      fonts:
        - asset: assets/fonts/inter/Inter_18pt-Thin.ttf
          weight: 100
        - asset: assets/fonts/inter/Inter_18pt-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/inter/Inter_18pt-Light.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter_18pt-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter_18pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/inter/Inter_18pt-Black.ttf
          weight: 900

  #  - family: Lato
  #   fonts:
  #     - asset: assets/fonts/Lato-Black.ttf
  #     - asset: assets/fonts/Lato-BlackItalic.ttf
  #       style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
