class PaysWidgetModel {
  final String indicatif;
  final String countryName;
  final String countryFlag;
  final String countryCode;
  final bool isInternational;
  final String flag;
  final int maxLength;
  PaysWidgetModel({
    required this.flag,
    required this.indicatif,
    required this.countryName,
    required this.countryFlag,
    required this.countryCode,
    required this.isInternational,
    required this.maxLength,
  });
}

List<PaysWidgetModel> africanCountries = [
  PaysWidgetModel(
    indicatif: '+237',
    countryName: 'Cameroun',
    countryFlag: 'cm',
    countryCode: 'CM',
    isInternational: false,
    flag: '🇨🇲',
    maxLength: 14,
  ),
  PaysWidgetModel(
    indicatif: '+241',
    countryName: 'Gabon',
    countryFlag: 'ga',
    countryCode: 'GA',
    isInternational: false,
    flag: '🇬🇦',
    maxLength: 13,
  ),
  PaysWidgetModel(
    indicatif: '+254',
    countryName: 'Kenya',
    countryFlag: 'ke',
    countryCode: 'KE',
    isInternational: false,
    flag: '🇰🇪',
    maxLength: 14,
  ),
  PaysWidgetModel(
    indicatif: '+228',
    countryName: 'Togo',
    countryFlag: 'tg',
    countryCode: 'TG',
    isInternational: false,
    flag: '🇹🇬',
    maxLength: 09,
  ),
  PaysWidgetModel(
    indicatif: '+233',
    countryName: 'Ghana',
    countryFlag: 'gh',
    countryCode: 'GH',
    isInternational: false,
    flag: '🇬🇭',
    maxLength: 10,
  ),
  PaysWidgetModel(
    indicatif: '+225',
    countryName: "Côte d'Ivoire",
    countryFlag: 'ci',
    countryCode: 'CI',
    isInternational: false,
    flag: '🇨🇮',
    maxLength: 10,
  ),
  PaysWidgetModel(
    indicatif: '+216',
    countryName: 'Tunisie',
    countryFlag: 'tn',
    countryCode: 'TN',
    isInternational: false,
    flag: '🇹🇳',
    maxLength: 11,
  ),
  PaysWidgetModel(
    indicatif: '+213',
    countryName: 'Algérie',
    countryFlag: 'dz',
    countryCode: 'DZ',
    isInternational: false,
    flag: '🇩🇿',
    maxLength: 13,
  ),
  PaysWidgetModel(
    indicatif: '+27',
    countryName: 'Afrique du Sud',
    countryFlag: 'za',
    countryCode: 'ZA',
    isInternational: false,
    flag: '🇿🇦',
    maxLength: 13,
  ),
  PaysWidgetModel(
    indicatif: '+20',
    countryName: 'Égypte',
    countryFlag: 'eg',
    countryCode: 'EG',
    isInternational: false,
    flag: '🇪🇬',
    maxLength: 12,
  ),
  PaysWidgetModel(
    indicatif: '+223',
    countryName: 'Mali',
    countryFlag: 'ml',
    countryCode: 'ML',
    isInternational: false,
    flag: '🇲🇱',
    maxLength: 13,
  ),
  PaysWidgetModel(
    indicatif: '+221',
    countryName: 'Sénégal',
    countryFlag: 'sn',
    countryCode: 'SN',
    isInternational: false,
    flag: '🇸🇳',
    maxLength: 13,
  ),
  PaysWidgetModel(
    indicatif: '+255',
    countryName: 'Tanzanie',
    countryFlag: 'tz',
    countryCode: 'TZ',
    isInternational: false,
    flag: '🇹🇿',
    maxLength: 12,
  ),
  PaysWidgetModel(
    indicatif: '+250',
    countryName: 'Rwanda',
    countryFlag: 'rw',
    countryCode: 'RW',
    isInternational: false,
    flag: '🇷🇼',
    maxLength: 13,
  ),
  PaysWidgetModel(
    indicatif: '+212',
    countryName: 'Maroc',
    countryFlag: 'ma',
    countryCode: 'MA',
    isInternational: false,
    flag: '🇲🇦',
    maxLength: 12,
  ),
  PaysWidgetModel(
    indicatif: '+226',
    countryName: 'Burkina Faso',
    countryFlag: 'bf',
    countryCode: 'BF',
    isInternational: false,
    flag: '🇧🇫',
    maxLength: 12,
  ),
  PaysWidgetModel(
    indicatif: '+258',
    countryName: 'Mozambique',
    countryFlag: 'mz',
    countryCode: 'MZ',
    isInternational: false,
    flag: '🇲🇿',
    maxLength: 13,
  ),
  PaysWidgetModel(
    indicatif: '+260',
    countryName: 'Zambie',
    countryFlag: 'zm',
    countryCode: 'ZM',
    isInternational: false,
    flag: '🇿🇲',
    maxLength: 13,
  ),
  PaysWidgetModel(
    indicatif: '+265',
    countryName: 'Malawi',
    countryFlag: 'mw',
    countryCode: 'MW',
    isInternational: false,
    flag: '🇲🇼',
    maxLength: 13,
  ),
  PaysWidgetModel(
    indicatif: '+220',
    countryName: 'Gambie',
    countryFlag: 'gm',
    countryCode: 'GM',
    isInternational: false,
    flag: '🇬🇲',
    maxLength: 12,
  ),
];

final searchGrantList = africanCountries;
